### ISSUE TITLE
explain how it works

### ISSUE THREAD

**Issue by Mago126** [sneksnake/CSharp-QR-Code-Discord-Scam-Bot#6]
explain how it works step by step ive compiled it

**Comment by Mago126** [comment]
like it says "Bot is ready to go!" What do i have to do now? Nothing happens

**Comment by sneksnake** [comment]
you need to set the token in the Config file with a bot with all intents

**Comment by Mago126** [comment]
> you need to set the token in the Config file with a bot with all intents

![image](https://user-images.githubusercontent.com/106020383/179425708-5e4262c5-c841-4d27-ab99-fa35db31c038.png)
do i have to put my channel webhook here? and if yes where?

**Comment by sneksnake** [comment]
if you can't figure it out maybe just don't do it ?
