### ISSUE TITLE
stucked at creating captcha

### ISSUE THREAD

**Issue by Mago126** [sneksnake/CSharp-QR-Code-Discord-Scam-Bot#9]
its stucked at creating a captcha 
![image](https://user-images.githubusercontent.com/106020383/179426253-0abe2471-868c-4b13-a181-0b089400b94c.png)
everything i did was ive uploaded custom emojis to my server and pasted my bot token thats all idk if i did something wrong its just stucked at captcha

**Comment by sneksnake** [comment]
no way

**Comment by Mago126** [comment]
> no way

bro tell us how to fix that

**Comment by sneksnake** [comment]
- [X] brain damage
- [X] actual migraine
- [X] no wayyyyy !!!
